name: SDK Publish (Unstable)

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install dotnet-setversion
        run: dotnet tool install -g dotnet-setversion

      - name: Restore packages
        run: dotnet restore

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: '2000.01.01'

      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create new milestone
        id: createmilestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ steps.semvers.outputs.patch }}

      - name: Create new version string
        id: version
        run: echo "::set-output name=number::$(echo ${{ steps.createmilestone.outputs.number }}-unstable.$(date +'%Y%m%d%H%M'))"

      - name: Set project version
        run: setversion ${{ steps.version.outputs.number }}

      - name: Generate sdk
        run: dotnet msbuild -target:GenerateSdk-Unstable

      - name: Build packages
        run: dotnet build -c Release

      - name: Publish to nuget
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Commit new changes to the repo
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git checkout -B openapi-unstable
          git add .
          git commit --allow-empty -m "Update unstable OpenAPI client"
          git push --force origin openapi-unstable
